window:
  padding:
    x: 10
    y: 10
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 1

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: SF Mono
    style:  Regular
  bold:
    family: SF Mono
    style:  Bold
  italic:
    family: SF Mono
    style:  Italic
  bold_italic:
    family: SF Mono
    style: Bold Italic
  size: 12
draw_bold_text_with_bright_colors: true

import:
  - ~/.config/alacritty/colors.yml

selection:
  save_to_clipboard: false

shell:
  program: /usr/bin/bash

key_bindings:
  - { key: Return, mods: Super|Shift, action: SpawnNewInstance }

